title: 'báo cáo tiểu luận '
description: abc
template:
  repo: bao-cao-tieu-luan-template
  name: bao-cao-tieu-luan
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
